name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl git wget htop gnupg python3 python3-pip python3-venv python-is-python3 \
            python3-dev graphviz libgraphviz-dev pkg-config \
            texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-xetex ghostscript

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install .
          install-lean
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Run tests
        run: python -m unittest discover -s ./tests
